CREATE DATABASE GC_BANCO
GO
USE GC_BANCO
GO
CREATE TABLE [dbo].[CARGO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](50) NULL,
	[USUARIO_ALTERACAO_ID] [bigint] NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
	[DATA_ALTERACAO] [datetime] NULL,
	[STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ENDERECO]    Script Date: 22/09/2023 12:51:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ENDERECO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CEP] [varchar](50) NULL,
	[UF] [varchar](2) NULL,
	[CIDADE] [varchar](100) NULL,
	[BAIRRO] [varchar](100) NULL,
	[NUMERO] [varchar](10) NULL,
	[LOGRADOURO] [varchar](100) NULL,
	[COMPLEMENTO] [varchar](100) NULL,
	[LATITUDE] [varchar](50) NULL,
	[LONGITUDE] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PESSOA]    Script Date: 22/09/2023 12:51:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PESSOA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ENDERECO_ID] [bigint] NULL,
	[NOME] [varchar](50) NOT NULL,
	[DOCUMENTO] [varchar](50) NULL,
	[HABILITACAO] [varchar](100) NULL,
	[SEXO] [varchar](1) NULL,
	[DATA_NASCIMENTO] [datetime] NULL,
	[TELEFONE_1] [varchar](50) NULL,
	[TELEFONE_2] [varchar](50) NULL,
	[EMAIL] [varchar](50) NULL,
	[NOME_TITULAR_CONTA] [varchar](100) NULL,
	[CONTA] [varchar](20) NULL,
	[AGENCIA] [varchar](20) NULL,
	[PIX] [varchar](100) NULL,
	[USUARIO_ALTERACAO_ID] [bigint] NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
	[DATA_ALTERACAO] [datetime] NULL,
	[STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USUARIO]    Script Date: 22/09/2023 12:51:45 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIO](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EMPRESA_ID] [bigint] NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[SENHA] [varchar](10) NOT NULL,
	[PERMISSAO] [int] NOT NULL,
	[NOME] [varchar](50) NULL,
	[USUARIO_ALTERACAO_ID] [bigint] NOT NULL,
	[DATA_CADASTRO] [datetime] NOT NULL,
	[DATA_ALTERACAO] [datetime] NULL,
	[STATUS] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CARGO] ON 
GO
INSERT [dbo].[CARGO] ([ID], [NOME], [USUARIO_ALTERACAO_ID], [DATA_CADASTRO], [DATA_ALTERACAO], [STATUS]) VALUES (1, N'MEDICO', 0, CAST(N'2023-09-22T12:45:42.233' AS DateTime), CAST(N'2023-09-22T12:45:42.233' AS DateTime), 1)
GO
SET IDENTITY_INSERT [dbo].[CARGO] OFF
GO
SET IDENTITY_INSERT [dbo].[ENDERECO] ON 
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (1, N'51130-010', N'PE', N'Recife', N'Boa Viagem', N'126', N'Rua Setúbal', N'CASA', N'-8.1401513', N'-34.9042591')
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (2, N'54753777', N'PE', N'CAMARAGIBE', N'VILA DA INABI', N'147', N'RUA DA LAMA', N'CASA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (3, N'54753777', N'PE', N'CAMARAGIBE', N'VILA DA INABI', N'147', N'RUA DA LAMA', N'CASA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (4, N'54753777', N'PE', N'CAMARAGIBE', N'VILA DA INABI', N'147', N'RUA DA LAMA', N'CASA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (5, N'54753-070', N'SP', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Oriente', N'CASA DOIDA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (6, N'54753-070', N'SP', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Oriente', N'CASA DOIDA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (7, N'54753-010', N'SP', N'Camaragibe', N'Nazaré', N'141', N'Rua Iara Amaral', N'CASA DOIDA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (8, N'54753-090', N'SP', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Sertão', N'CASA DOIDA', NULL, NULL)
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (9, N'54753-070', N'PE', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Oriente', N'CASA DOIDA', N'-8.0163216', N'-34.9661841')
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (10, N'54753-070', N'PE', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Oriente', N'CASA DOIDA', N'-8.0163216', N'-34.9661841')
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (11, N'54753-090', N'PE', N'Camaragibe', N'Nazaré', N'141', N'Rua Grande Sertão', N'CASA DOIDA', N'-8.0179851', N'-34.9628053')
GO
INSERT [dbo].[ENDERECO] ([ID], [CEP], [UF], [CIDADE], [BAIRRO], [NUMERO], [LOGRADOURO], [COMPLEMENTO], [LATITUDE], [LONGITUDE]) VALUES (12, N'51130-010', N'PE', N'Recife', N'Boa Viagem', N'141', N'Rua Setúbal', N'CASA DOIDA', N'-8.1366561', N'-34.9025622')
GO
SET IDENTITY_INSERT [dbo].[ENDERECO] OFF
GO
SET IDENTITY_INSERT [dbo].[PESSOA] ON 
GO
INSERT [dbo].[PESSOA] ([ID], [ENDERECO_ID], [NOME], [DOCUMENTO], [HABILITACAO], [SEXO], [DATA_NASCIMENTO], [TELEFONE_1], [TELEFONE_2], [EMAIL], [NOME_TITULAR_CONTA], [CONTA], [AGENCIA], [PIX], [USUARIO_ALTERACAO_ID], [DATA_CADASTRO], [DATA_ALTERACAO], [STATUS]) VALUES (2, 1, N'Edson Gouveia de Brito', N'09307306400', N'M', N'M', CAST(N'2023-01-01T00:00:00.000' AS DateTime), N'81995253701', N'81995253701', N'edsongouveiabrito@gmail.com', N'EDSON G', N'4001', N'010984847', N'edsongouveiabrito@gmail.com', 0, CAST(N'2023-04-10T12:54:33.450' AS DateTime), CAST(N'2023-04-10T12:55:16.500' AS DateTime), 1)
GO
SET IDENTITY_INSERT [dbo].[PESSOA] OFF
GO
SET IDENTITY_INSERT [dbo].[USUARIO] ON 
GO
INSERT [dbo].[USUARIO] ([ID], [EMPRESA_ID], [EMAIL], [SENHA], [PERMISSAO], [NOME], [USUARIO_ALTERACAO_ID], [DATA_CADASTRO], [DATA_ALTERACAO], [STATUS]) VALUES (1, 1, N'edsongouveiabrito@gmail.com', N'123', 1, N'Edson Gouveia de Brito', 0, CAST(N'2023-03-31T12:48:07.507' AS DateTime), NULL, 1)
GO
SET IDENTITY_INSERT [dbo].[USUARIO] OFF
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__USUARIO__161CF7241F6695DB]    Script Date: 22/09/2023 12:51:45 ******/
ALTER TABLE [dbo].[USUARIO] ADD UNIQUE NONCLUSTERED 
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD FOREIGN KEY([ENDERECO_ID])
REFERENCES [dbo].[ENDERECO] ([ID])
GO
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD FOREIGN KEY([ENDERECO_ID])
REFERENCES [dbo].[ENDERECO] ([ID])
GO
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD FOREIGN KEY([ENDERECO_ID])
REFERENCES [dbo].[ENDERECO] ([ID])
GO
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD FOREIGN KEY([ENDERECO_ID])
REFERENCES [dbo].[ENDERECO] ([ID])
GO
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD FOREIGN KEY([ENDERECO_ID])
REFERENCES [dbo].[ENDERECO] ([ID])
GO
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD FOREIGN KEY([EMPRESA_ID])
REFERENCES [dbo].[EMPRESA] ([ID])
GO
